// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOADxPYl_nFoilvQgGjrIkFwXazvIJPY',
    appId: '1:569618605179:web:5b37fd0f774aff7ed56ede',
    messagingSenderId: '569618605179',
    projectId: 'fir-flutter-codelab-fec88',
    authDomain: 'fir-flutter-codelab-fec88.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-fec88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjtmdhEDF5N6gNsZ72C4UFtr1BWZATDQ',
    appId: '1:569618605179:android:b18b45b36051f07cd56ede',
    messagingSenderId: '569618605179',
    projectId: 'fir-flutter-codelab-fec88',
    storageBucket: 'fir-flutter-codelab-fec88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3HTCpugFuJzWLVIaB3-yDwDy-codl6Zk',
    appId: '1:569618605179:ios:11e0b1b9d553d284d56ede',
    messagingSenderId: '569618605179',
    projectId: 'fir-flutter-codelab-fec88',
    storageBucket: 'fir-flutter-codelab-fec88.appspot.com',
    iosClientId:
        '569618605179-help7g1cg5nr6uejlca9hccr4achqv18.apps.googleusercontent.com',
    iosBundleId: 'com.example.tareaFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3HTCpugFuJzWLVIaB3-yDwDy-codl6Zk',
    appId: '1:569618605179:ios:11e0b1b9d553d284d56ede',
    messagingSenderId: '569618605179',
    projectId: 'fir-flutter-codelab-fec88',
    storageBucket: 'fir-flutter-codelab-fec88.appspot.com',
    iosClientId:
        '569618605179-help7g1cg5nr6uejlca9hccr4achqv18.apps.googleusercontent.com',
    iosBundleId: 'com.example.tareaFirebaseFlutter',
  );
}
